# Generated by Django 3.2.12 on 2024-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=80)),
                ('cognome', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
