# Generated by Django 5.0.6 on 2024-06-23 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caratteristica',
            fields=[
                ('tag', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='utente',
            name='isAlbergatore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utente',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Albergo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('localita', models.CharField(max_length=100)),
                ('numStelle', models.IntegerField(default=0)),
                ('albergatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCamera', models.IntegerField()),
                ('postiLetto', models.IntegerField(default=1)),
                ('tempoCancellazione', models.IntegerField(default=10)),
                ('prezzo', models.FloatField()),
                ('albergo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.albergo')),
            ],
            options={
                'unique_together': {('numeroCamera', 'albergo')},
            },
        ),
        migrations.CreateModel(
            name='CameraCaratteristiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.camera')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.caratteristica')),
            ],
        ),
    ]
