# Generated by Django 5.0.6 on 2024-06-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_caratteristica_utente_isalbergatore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='tipologia',
            field=models.CharField(choices=[('SINGOLA', 'Singola'), ('DOPPIA', 'Doppia'), ('JUNIOR SUITE', 'Junior Suite'), ('SUITE', 'Suite')], default='SINGOLA', max_length=20),
        ),
    ]
