# Generated by Django 5.0.6 on 2024-06-25 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_camera_tipologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataInizio', models.DateField()),
                ('dataFine', models.DateField()),
                ('isAttiva', models.BooleanField(default=False)),
                ('totale', models.FloatField(default=0.0)),
                ('numPersone', models.IntegerField(default=1)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.camera')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.utente')),
            ],
        ),
    ]
