# Generated by Django 5.0.6 on 2024-06-26 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_prenotazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='dataCancellazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='dataFine',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='dataInizio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
