# Generated by Django 5.0.6 on 2024-06-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_prenotazione_datacancellazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='prezzo',
            field=models.FloatField(default=0.0),
        ),
    ]
