# Generated by Django 5.0.6 on 2024-06-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_utente_groups_utente_is_active_utente_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
