# Generated by Django 5.0.6 on 2024-07-01 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_camera_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albergo',
            name='numStelle',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
