# Generated by Django 5.0.6 on 2024-07-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_albergo_numstelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='descrizione',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='CameraCaratteristiche',
        ),
        migrations.DeleteModel(
            name='Caratteristica',
        ),
    ]
