# Generated by Django 5.0.6 on 2024-07-11 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_camera_descrizione_delete_cameracaratteristiche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='dataPrenotazione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
