# Generated by Django 5.0.6 on 2024-07-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_prenotazione_dataprenotazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albergo',
            options={'verbose_name': 'Albergo', 'verbose_name_plural': 'Alberghi'},
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Camera', 'verbose_name_plural': 'Camere'},
        ),
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'verbose_name': 'Prenotazione', 'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AlterModelOptions(
            name='utente',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
    ]
