# Generated by Django 5.0.6 on 2024-07-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_albergo_options_alter_camera_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='totale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
